image: ubuntu
version: "b{build}g1.10"
build: off
pull_requests: 
  do_not_increment_build_number: true
clone_depth: 50
stack: go 1.10, mysql, redis

init:
  - git config --global core.autocrlf input

install:
  - go get -d -v github.com/Gigamons/Kaoiji

test_script:
  - go build -v /home/appveyor/projects/kaoiji/kaoiji.go