image: ubuntu

version: "{build}"

build: off

init:
  - git config --global core.autocrlf input

stack: go 1.10, mysql, redis

install:
  - go get github.com/Gigamons/Kaoiji
  - go get %GOPATH%/src/Gigamons/Kaoiji/...

test_script:
  - go build -v %GOPATH%/src/Gigamons/Kaoiji/kaoiji.go